name: bilibili
description: 不完整版本的哔哩哔哩.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# http
  dio:
# CPU锁定
  wakelock:
# 文件选择
  file_picker:
# 提示
  fluttertoast:
# 下拉刷新
  pull_to_refresh:
# 内存存储
  shared_preferences:
#
  fijkplayer:
#
  fijkplayer_skin:
# 轮播
  flutter_swiper_null_safety:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - images/
  uses-material-design: true

  fonts:
    - family: bilibili
      fonts:
        - asset: assets/icons/iconfont.ttf